In [486]:

def preprocess_data(path):
    #reading motifs from a FASTA file
    df = pd.read_csv(path, header=None)
    #Converitng a dataframe into a numpy array
    arr1= np.array(df.iloc[:,:])
    newarr=[]
    for i in range (len(arr1)):
          temp=np.array_str(arr1[i])
          temp2=filter(str.isalnum, temp)
          arr2=np.array(list(temp2))
          newarr.append(arr2)
    mot=np.array(newarr)
    type(mot)
    return mot



# Function to calculate Probability Frequency Matrix

def pfm_compute(mot):
    count_A=0
    count_T=0
    count_G=0
    count_C=0

    pfm=np.zeros([4,len_seq])
    for i in range (len_seq):
        count_A=0
        count_T=0
        count_G=0
        count_C=0
        for j in range (len(mot)):
            if(mot[j:j+1,i:i+1]=="A"):
                count_A=count_A+1
            if(mot[j:j+1,i:i+1]=="G"):
                count_G=count_G+1
            if(mot[j:j+1,i:i+1]=="C"):
                count_C=count_C+1
            if(mot[j:j+1,i:i+1]=="T"):
                count_T=count_T+1
        
        pfm[0:1,i:i+1]=count_A
        pfm[1:2,i:i+1]=count_G
        pfm[2:3,i:i+1]=count_T
        pfm[3:4,i:i+1]=count_C
    return pfm


# Calculating ppm from pfm
def ppm_compute(pfm):
    ppm=np.divide(pfm,len(arr1))
    return ppm


# Calculating PWM from ppm
def pwm_compute(ppm):
    pwm=np.divide(ppm,0.25)
    pwm=np.log(pwm) /np.log(2)
    pwm[pwm < 0] = 0
    return pwm
 



In [488]:

path="motifs.txt"

mot=preprocess_data(path)
len_seq=mot.shape[1] 
print("Position frequency matrix : ", pfm_compute(mot))
print("Position probability matrix : ", ppm_compute(pfm))
print("Position weight matrix: ", pwm_compute(ppm))

Position frequency matrix :  [[3. 6. 1. 0. 2. 4. 2. 1. 1. 2.]
 [1. 0. 4. 4. 3. 1. 6. 2. 3. 6.]
 [0. 0. 4. 5. 2. 3. 0. 3. 4. 2.]
 [6. 4. 1. 1. 3. 2. 2. 4. 2. 0.]]
Position probability matrix :  [[0.3 0.6 0.1 0.  0.2 0.4 0.2 0.1 0.1 0.2]
 [0.1 0.  0.4 0.4 0.3 0.1 0.6 0.2 0.3 0.6]
 [0.  0.  0.4 0.5 0.2 0.3 0.  0.3 0.4 0.2]
 [0.6 0.4 0.1 0.1 0.3 0.2 0.2 0.4 0.2 0. ]]
Position weight matrix:  [[0.26303441 1.26303441 0.         0.         0.         0.67807191
  0.         0.         0.         0.        ]
 [0.         0.         0.67807191 0.67807191 0.26303441 0.
  1.26303441 0.         0.26303441 1.26303441]
 [0.         0.         0.67807191 1.         0.         0.26303441
  0.         0.26303441 0.67807191 0.        ]
 [1.26303441 0.67807191 0.         0.         0.26303441 0.
  0.         0.67807191 0.         0.        ]]


C:\Users\Ahtisham Abbasi\Anaconda3\lib\site-packages\ipykernel_launcher.py:60: RuntimeWarning: divide by zero encountered in log
